### ISSUE TITLE
How to set the database connection URL?

### ISSUE THREAD

**Issue by preston** [AEGISnetInc/WildFHIR#10]
@rettema @GumptionWare Hi! How do we set WildFHIR server's database connection URL? I'm assuming it'd be something like `databaseUrl=jdbc:mysql://wildfhir-mysql:3306/wildfhir`

Preston
CC @danielhmendoza01

**Comment by rettema** [comment]
@preston You're not far off. The wiki installation page describes this - https://github.com/AEGISnetInc/WildFHIR/wiki/Installation - towards the bottom of the page.

The full connection url is "**jdbc:mysql://localhost:3306/wildfhirr4?useUnicode=yes&amp;useSSL=false&amp;verifyServerCertificate=false&amp;allowPublicKeyRetrieval=true**". If you have the MySQL database on a different machine/host, update "localhost".

**Comment by preston** [comment]
@rettema Thanks! What's the environment variable name to set this?

**Comment by rettema** [comment]
@preston configuration via environment variables is still pending.
