### ISSUE TITLE
Public images?

### ISSUE THREAD

**Issue by preston** [AEGISnetInc/WildFHIR#4]
I'm curating the WildFHIR listing in HL7 Foundry and would like to add official docker images and default configurations for wiring into other services. Are these already available?

**Comment by Interopguy** [comment]
Hello Preston, we have a number of items which will be addressed in the coming weeks; our short term focus has been tasking to get ready for DevDays 2024.  We will provide an update to this ticket, when we have an estimate on having the container version. There are a few other items that will be included in the next deployment.

**Comment by preston** [comment]
Hi @Interopguy , Here's a HAPI-based tutorial that I'd like to replicate with WildFHIR. We just got Spark loaded, but I think the combination of WildFHIR and HAPI would likely be a better combination of options for some higher-level RI distribution use cases due to the level of validation.

But in any event, could you take a look at the current WildFHIR listing on Foundry (https://foundry.hl7.org/) and provide more of the missing metadata? Here's the checklist: https://skycapp.com/developer/product-submission-checklist/

**Comment by GumptionWare** [comment]
On it. Thanks Preston!

JH

**Comment by GumptionWare** [comment]
Hey @preston, you said, "Here's a HAPI-based tutorial that I'd like to replicate with WildFHIR." 

Where is that tutorial?

**Comment by preston** [comment]
@GumptionWare Ah good catch :) That tutorial is at https://skycapp.com/tutorials/downloading-and-running-a-product-stack-hapi-fhir/ 
Generalized instructions for packaging products to support the same type of automated distribution and deployment: https://skycapp.com/developer/product-packaging-examples/

**Comment by GumptionWare** [comment]
Thanks @preston. Those are exactly the details we need.

**Comment by GumptionWare** [comment]
Hey @preston, Richard has uploaded a set of Docker images here: https://hub.docker.com/repositories/aegisnetinc

We have the information for the "Instructions" and "Configuration Wizard" sections that we look forward to going over with you on our call tomorrow.

**Comment by preston** [comment]
@GumptionWare Looking forward to it!

**Comment by rettema** [comment]
Daniel and Preston have published the Skycapp tutorial for WildFHIR CE - https://skycapp.com/tutorials/downloading-and-running-a-product-stack-wildfhir

The WildFHIR CE Docker images are now current with version 0.3.1 - https://hub.docker.com/u/aegisnetinc
