### ISSUE TITLE
Add configurability via environment variables.

### ISSUE THREAD

**Issue by preston** [AEGISnetInc/WildFHIR#8]
Allow for the overriding of default values, if any, for settings commonly needing to be changed when run in different environments. Often times this includes things like database connection URLs and credentials. This guide may be helpful: https://skycapp.com/developer/product-packaging-examples/

README documentation is also _very_ much appreciated, as this is one of the first places users look for configuration guidance. :)

**Comment by rettema** [comment]
WildFHIR CE version 0.3.1 released with updates to support Docker configuration via environment variables.
